global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "poc-observability-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["172.17.0.1:8080"]
        labels:
          application: poc-observability