spring:
  application:
    name: svc-poc-observability
server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure.include: "health,info,prometheus"
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    prometheus:
      enabled: true

logging:
  level:
    root: INFO
    web: INFO
    org.springframework.web.servlet.DispatcherServlet: INFO
