server:
  port: ${PORT:8080}
  servlet.context-path: /api

management:
  endpoints:
    web:
      exposure.include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true

logging:
  level:
    root: INFO
    web: INFO
    org.springframework.web.servlet.DispatcherServlet: INFO

spring:
  application:
    name: svc-poc-observability




